[package]
name = "drop"
version = "0.2.5"
authors = ["Bryan Gilbert <gilbertw1@gmail.com>"]
build = "build.rs"

[dependencies]
rand = "0.3.15"
config = "0.6"
clap = "2.25.1"
nix = "0.9.0"
c_vec = "~1.2"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.2"
cocoa = "0.9.2"

[build-dependencies]
clap = "2.25.1"
