[package]
name = "drop"
version = "0.1.0"
authors = ["Bryan Gilbert <gilbertw1@gmail.com>"]
build = "build.rs"

[dependencies]
rand = "0.3.15"
config = "0.4"
clap = "~2.19.0"
lazy_static = "0.2.2"

[build-dependencies]
clap = "2.18"
lazy_static = "0.2"